version: '3'

services:
  db:
    image: postgres
    container_name: aiohttp_chat_db
  web:
    build: .
    container_name: aiohttp_chat_web
    volumes:
      - /src
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
