version: '3'

services:
  db:
    image: postgres:latest
    container_name: aiochat_db
    expose:
      - "5432"
  web:
    build: .
    container_name: aiochat_web
    environment:
      WEB_HOST: "0.0.0.0"
      WEB_PORT: "8000"
    volumes:
      - /src
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python -u server.py
